// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAOybI1v6L62gP3a16B7ks4xAhCyC0d6gE',
    appId: '1:521606417855:web:75f4c1b46847837175250a',
    messagingSenderId: '521606417855',
    projectId: 'upchat-backend-2',
    authDomain: 'upchat-backend-2.firebaseapp.com',
    storageBucket: 'upchat-backend-2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAqGkpYxCMGeYaGfmisqOV9mNjIPTr4OiE',
    appId: '1:521606417855:android:487a2567c4597f7a75250a',
    messagingSenderId: '521606417855',
    projectId: 'upchat-backend-2',
    storageBucket: 'upchat-backend-2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA3kDGtzg8-_H_O2ybLlKo8bZ47UfAVImY',
    appId: '1:521606417855:ios:37050e55239b40f475250a',
    messagingSenderId: '521606417855',
    projectId: 'upchat-backend-2',
    storageBucket: 'upchat-backend-2.appspot.com',
    iosBundleId: 'com.example.upchat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA3kDGtzg8-_H_O2ybLlKo8bZ47UfAVImY',
    appId: '1:521606417855:ios:db61957db99a174175250a',
    messagingSenderId: '521606417855',
    projectId: 'upchat-backend-2',
    storageBucket: 'upchat-backend-2.appspot.com',
    iosBundleId: 'com.example.upchat.RunnerTests',
  );
}
